const CONSTANT = {
    MOBILEDVELOPMENT: "MOBILEDVELOPMENT",
    WEBDEV:"WEBDEV",
    UIUX:"UIUX",
    PRESENTATION:'PRESENTATION',
    TESTIMONIAL:'TESTIMONIAL',
    MOBILEAPP:'MOBILEAPP',
    SELECTED:"SELECTED"
}
export default CONSTANT 